### ISSUE TITLE
An API to manage most base collection types

### ISSUE THREAD

**Issue by smarie** [ilevkivskyi/typing_inspect#10]
Collection types are an important special case of Generic types. In [parsyfiles](https://github.com/smarie/python-parsyfiles) I ended up writing functions to easily access
 * the type of the key in a `Mapping`
 * the type of the items in `Mapping` (values, not keys), and `Iterable` (but I should probably use `Container` instead)

The indent was to at least support `Dict[KT, VT]`, `List[VT]`, `Set[VT]`, and `Tuple[VT1, VT2, VT3...]`.

Maybe such as API could be of some interest for `typing_inspect` users ? 

For details about how I used it, please see `_extract_collection_base_type` in https://github.com/smarie/python-parsyfiles/blob/master/parsyfiles/type_inspection_tools.py. Some tests are available [here](https://github.com/smarie/python-parsyfiles/tree/master/parsyfiles/tests/unittests/test_type_inspection_tools.py)

However the way I did it is probably not the best for an api, probably it would be better to provide individual functions such as `get_mapping_inner_types` and `get_container_inner_types`. An interesting thing to keep, though, is the capability to detect underspecified types such as `Dict` (and not `Dict[A, B]`) and to throw a `TypeInformationRequiredError`. See above file for details.

**Comment by ilevkivskyi** [comment]
But this would be a simple combination of ``get_args`` and ``get_origin``. I think we should get better API for more general functions rather than focus on many specialized functions.

**Comment by Stewori** [comment]
Yet again there is something in pytypes I'd like to point out.
[pytypes.get_iterable_itemtype](https://github.com/Stewori/pytypes/blob/master/pytypes/type_util.py#L80) might be of some help, not the entire solution to this request though.

**Comment by smarie** [comment]
Thanks ! yes @ilevkivskyi you are right, but that might be a "frequent" specialized request. See the `collections` module: it is extremely useful, although specialized on collections. @Stewori I'll have a look

**Comment by Stewori** [comment]
@smarie it just occurred to me that pytypes.get_iterable_itemtype is only about `iterable` from collections, not about `Iterable` from `typing`. Regarding a generic subtype of `Iterable` from typing, pytypes also has a good (?) way to retrieve the item type, but that's not conveniently accessible via API right now IIRC.

**Comment by Stewori** [comment]
There are now functions in [pytypes](https://github.com/Stewori/pytypes) to accomplish this:
- [pytypes.get_Generic_itemtype](https://github.com/Stewori/pytypes#get_generic_itemtypesq-simplifytrue)
- [pytypes.get_Mapping_key_value](https://github.com/Stewori/pytypes#get_mapping_key_valuemp)
- [pytypes.get_Generic_parameters](https://github.com/Stewori/pytypes/blob/master/pytypes/type_util.py#L173)
While the purpose of the first two is hopefully obvious, the third retrieves the parameters of a generic, viewed as a specific superclass.

I suppose this essentially solves this issue, once released.

**Comment by ilevkivskyi** [comment]
OK, I think we can close this for now, since ``pytypes`` provide the functionality.
