### ISSUE TITLE
is_literal broken with new typing_extensions

### ISSUE THREAD

**Issue by sanderr** [ilevkivskyi/typing_inspect#100]
`typing_inspect.is_literal` is broken when `typing-extensions-4.6.0` is installed. The following simple check fails. Installing `typing-extensions-4.5.0` makes it work.
```python
import typing
import typing_inspect


assert typing_inspect.is_literal_type(typing.Literal)  # this fails on Python 3.9.15 with typing_extensions==4.6.0
```

While `typing_extensions` made some changes in their latest release I believe it didn't introduce any backwards incompatible changes and I would argue the cause is a bug in `typing_inspect`. It seems to count on `typing.Literal` and `typing_extensions.Literal` being the same. It imports `Literal` from `typing_extensions` ([here](https://github.com/ilevkivskyi/typing_inspect/blob/beaa4a4a0e10cc4f2b3657e8ad7c772cf4d03a7b/typing_inspect.py#L46)) and uses that for the `is_literal` check ([here](https://github.com/ilevkivskyi/typing_inspect/blob/beaa4a4a0e10cc4f2b3657e8ad7c772cf4d03a7b/typing_inspect.py#L238)). As far as I can figure out this assumption is unfounded as it was never documented that the two types would be the same, they just happened to be so for a while.

`typing-extensions-4.6.0` was released earlier today. According to its changelog it includes a bugfix on `typing_extensions.Literal`. Indeed, while on `typing-extensions-4.5.0` `typing.Literal is typing_extensions.Literal` this is no longer the case for the new version. As far as I can tell they did not introduce any backwards incompatible changes.

I tested this on Python 3.9.15. The issue does not seem to be present on 3.10.10, there `typing.Literal is typing_extensions.Literal` still holds.

EDIT: shifted the text around a bit in an effort to make it more readable

**Comment by sanderr** [comment]
Pydantic seems to have a similar check, potentially relevant discussion at https://github.com/pydantic/pydantic/issues/5821#issuecomment-1558520974

**Comment by AlexWaygood** [comment]
You'll probably want a fix similar to https://github.com/pydantic/pydantic/pull/5826

**Comment by ilevkivskyi** [comment]
Yeah. I will make a PR soon.
