### ISSUE TITLE
Broken with Python 3.6.3

### ISSUE THREAD

**Issue by lhupfeldt** [ilevkivskyi/typing_inspect#12]
On python 3.6.3 import of private '_gorg' is failing.
See https://travis-ci.org/lhupfeldt/multiconf/jobs/284627902
This module should be merged into typing or typing should provide public APIs for the methods needed by this module.

**Comment by ilevkivskyi** [comment]
Yes, sorry, I am aware of this, but didn't have time to fix it. Will try to find time on this weekend.

**Comment by lhupfeldt** [comment]
Quickest reply ever on a bug report :)

**Comment by ilevkivskyi** [comment]
OK, I published the new version on PyPI, please test.

**Comment by lhupfeldt** [comment]
Thank you, all tests are green.
