### ISSUE TITLE
New method is_nonable(t)

### ISSUE THREAD

**Issue by smarie** [ilevkivskyi/typing_inspect#14]
This method would return `True` if

 * t is the `NoneType` (`t is type(None)`)
 * t is a (possibly nested) `Union` to `NoneType` (this can be the result of using the `Optional` keyword or of an explicit `Union[type(None), ....]`
 * t is a `TypeVar` with either a `bound` or a `constraints` set, and one of them is nonable

**Comment by smarie** [comment]
Something like this

```python
def is_nonable(typ):
    """  Checks if a type is nonable  """
    return (typ is type(None)) \
           or (is_union_type(typ) and any(is_pep484_nonable(tt) for tt in typ.__args__)) \
           or (is_typevar(typ) and
               ((hasattr(typ, '__bound__') and is_pep484_nonable(typ.__bound__))
                or
                (hasattr(typ, '__constraints__') and any(is_pep484_nonable(tt) for tt in typ.__constraints__)))
               )
```

**Comment by smarie** [comment]
Not sure if we should use get_args with evaluate=True or False in this case.

**Comment by smarie** [comment]
Even better if you think that it makes sense: in order to support nesting of both Unions and TypeVars, I suggest to provide a companion function `resolve_union_and_typevar` (that is useful on its own) and rely on it:

```python
def resolve_union_and_typevar(typ) -> Tuple[Any, ...]:
    """
    If typ is a TypeVar,
     * if the typevar is bound, return resolve_union_and_typevar(bound)
     * if the typevar has constraints, return a tuple containing all the types listed in the constraints (with
     appropriate recursive call to resolve_union_and_typevar for each of them)
     * otherwise return (object, )

    If typ is a Union, return a tuple containing all the types listed in the union (with
     appropriate recursive call to resolve_union_and_typevar for each of them)

    Otherwise return (typ, )
    
    :param typ: 
    :return: 
    """
    if is_typevar(typ):
        if hasattr(typ, '__bound__') and typ.__bound__ is not None:
            return resolve_union_and_typevar(typ.__bound__)
        elif hasattr(typ, '__constraints__') and typ.__constraints__ is not None:
            return tuple(typpp for c in typ.__constraints__ for typpp in resolve_union_and_typevar(c))
        else:
            return object,
    elif is_union_type(typ):
        # do not use typ.__args__, it may be wrong
        # the solution below works even in typevar+config cases such as u = Union[T, str][Optional[int]]
        return get_args(typ, evaluate=True)
    else:
        return typ,

def is_pep484_nonable(typ):
    """
    Checks if a given type is nonable, meaning that it explicitly or implicitly declares a Union with NoneType.
    Nested TypeVars and Unions are supported.

    :param typ:
    :return:
    """
    if typ is type(None):
        return True
    elif is_typevar(typ) or is_union_type(typ):
        return any(is_pep484_nonable(tt) for tt in resolve_union_and_typevar(typ))
    else:
        return False
```

**Comment by ilevkivskyi** [comment]
TBH, this API looks a bit too special for me. Do we really need the `TypeVar` part hard-wired? I would propose to split this into two parts:
* `is_optional` would return if a type is a union containing `None`
* Add two other functions `get_bound` and `get_constraints` that will work with type variables.
Then a user can easily combine these two depending on whether one wants to recurse into type variables or not.

**Comment by smarie** [comment]
From a practical point of view I do not think that users make a difference between a type hint of a certain type ("normal" hints) and a type hint of another type (a TypeVar). They are "just" type hints, and users (at least, myself :) ) want to know what is allowed by this type hint and what is not. 

However if you do not consider that this is the role of typing-inspect, maybe it is the kind of higher-level API that should go into 'usability' libraries such as pytypes / enforce / ... ? If you think so, I will open a corresponding ticket in pytypes.

**Comment by smarie** [comment]
By the way I suggested to use `is_nonable` rather than `is_optional` since `Optional` does not actually mean optional: it can be used with mandatory arguments. 

However this naming discussion should happen (and actually is happening) in the typing project, it is fair to have typing_inspect follow closely whatever naming convention is used in typing.

**Comment by smarie** [comment]
Ok, I'll have a try one of these days. To implement `is_optional` I will have to at least rely on some kind of `flatten_union` utility method to retrieve all alternatives of possibly nested unions.

**Comment by smarie** [comment]
Back from a long and busy sequence.. To try to close this topic, we are basically stuck between two alternatives here, and I would need a choice to submit a pull request:
 - either implement `is_optional` as non-recursive: it returns `True` only if the type is the none type, or a direct union to the none type. In that case I suggest to add the following warning in the documentation:
```
Warning: this method will return a misleading `False` if `tp` is a `TypeVar` bound or constrained to an optional type, or if `tp` is a `Union` to such a `TypeVar`, or a `Union` to an optional type (nesting).
```
 - or rely on a `flatten_union_and_typevars` method. I do not think that doing only half of this (flattening the unions but not the type vars) would make sense. But we can decide to keep this method private (just for use within `is_optional`) if you think that this method is not of interest to the public API.

Finally concerning implementation principles, shall we raise a `TypeError` in `get_bound` / `get_constraints` if `not is_typevar(tp)` ?

**Comment by ilevkivskyi** [comment]
> either implement `is_optional` as non-recursive

I would rather call it `is_optional_type`. I don't think there is a need a specific warning in the docs. Just a clear description of semantics would be enough.
