### ISSUE TITLE
Get all compliant types

### ISSUE THREAD

**Issue by smarie** [ilevkivskyi/typing_inspect#16]
As opposed to previous posts, this time I created an issue directly in `pytypes` first: https://github.com/Stewori/pytypes/issues/31

However I had some afterthoughts: maybe this feature is actually enough 'core'-related (and resembles too much `__subclasses__()`) to be implemented outside of `typing_inspect`?

Feel free to close if it is too 'high-level'.

**Comment by smarie** [comment]
Answering my own post: if we follow the same policy than #9 , then this should not be in `typing_inspect` but in pytypes. Sorry for spotting it just now

**Comment by ilevkivskyi** [comment]
I think this should indeed be in `pytypes` and/or other high-level libs.
