### ISSUE TITLE
Broken on 3.7b2

### ISSUE THREAD

**Issue by Fuyukai** [ilevkivskyi/typing_inspect#17]
```
    from typing import (
ImportError: cannot import name 'CallableMeta' from 'typing' (/usr/lib64/python3.7/typing.py)
```

I assume this is because of typing module changes.

**Comment by ilevkivskyi** [comment]
I am sorry for this! This is a known issue, I will try to find time to fix it before the next beta.

**Comment by ilevkivskyi** [comment]
@Fuyukai I have opened PR https://github.com/ilevkivskyi/typing_inspect/pull/18 to support Python 3.7. Could you please review it? I would be grateful if you play with it and report any diferences in semantics from previous versions of Python.
