### ISSUE TITLE
Add ability to inspect TypedDict keys and their totality

### ISSUE THREAD

**Issue by JakobGM** [ilevkivskyi/typing_inspect#19]
It would be nice to somehow be able to inspect the specified type annotations of a ``TypedDict`` class instance. Let's say you have the following typed dictionary:

```python
class FooRequired(TypedDict):
    bar: str

class Foo(FooRequired, total=False):
    baz: int
```

Providing: 
- ``required_dict_keys(Foo) == {'bar': str}``
- ``optional_dict_keys(Foo) == {'baz': int}``
- ``dict_keys(Foo) == {'bar': str, 'baz': int}``

Not necessarily this API (it was just the first thing that I imagined), but something that would result in the same capabilities.

The rational is that this could enable ``TypedDict`` classes to be used as schema specification for untrusted JSON/YAML/config sources.

Thanks in advance!

**Comment by ilevkivskyi** [comment]
Unfortunately, current `TypedDict` API doesn't allow to find if a given key is required or not. But all keys and types can be easily extracted, see #21

**Comment by JakobGM** [comment]
Okay, this way you can check for forbidden keys. Thanks for investing your time in this, @ilevkivskyi!
