### ISSUE TITLE
Python 3.7 compatible release

### ISSUE THREAD

**Issue by robjampar** [ilevkivskyi/typing_inspect#20]
Hey, any chance we can get a new release of this on pip with the 3.7 support a bit early?
3.7-rc is out - i cant see Dataclasses changing, and it would save me a lot of work if was released (am building 3.7 updates and setup.py does not play well with git+url for dependencies of dependencies)

**Comment by ilevkivskyi** [comment]
0.3.1 was actually already Python 3.7 compatible. I just released 0.4.0 where I added Python 3.7 to the classifiers.
