### ISSUE TITLE
get_args() doesn't work with Union in 3.6

### ISSUE THREAD

**Issue by 1st1** [ilevkivskyi/typing_inspect#24]
### In 3.7:

```pycon
>>> typing_inspect.get_args(typing.List[typing.Union[str, bytes]])
(typing.Union[str, bytes],)
```

### In 3.6:

```pycon
>>> typing_inspect.get_args(typing.List[typing.Union[str, bytes]])
((typing.Union, <class 'str'>, <class 'bytes'>),)
```

**Comment by ilevkivskyi** [comment]
This is kind of a feature, by default, on Python 3.6 `get_args` returns a lazy internal representation, to get what you want, pass `evaluate=True`:
```python
>>> typing_inspect.get_args(typing.List[typing.Union[str, bytes]], evaluate=True)
(typing.Union[str, bytes],)
```
You can find few examples in the docstring.

**Comment by 1st1** [comment]
I see, thanks for pointing this out!

In general, I think that the defaults should be picked to make it easier to write code that works in all Python versions.  So I was expecting that `get_args` works the same all the time.

Closing this issue.
