### ISSUE TITLE
What is get_origin(typing.Dict) meant to return?

### ISSUE THREAD

**Issue by jbasko** [ilevkivskyi/typing_inspect#27]
In Python 3.6.6, `get_origin(typing.Dict)` returns `typing.Dict`, but in Python 3.7.0 it returns `dict`.
Is that by design?

**Comment by ilevkivskyi** [comment]
This is mostly intentional. This reflects the changes in `typing` module after PEP 560. I was thinking about some kind of a compatibility flag, but I am not sure this is needed. What is your use case for this?

**Comment by jbasko** [comment]
I'm generating code for a simpler API around boto3 with dataclasses and the generated code includes type descriptions because in my serialisers and deserialisers I wanted the parsing to be based on expected types.

Here's where I use typing_inspect:
https://github.com/jbasko/autoboto/blob/typing_inspect/botogen/autoboto_template/core/type_info.py#L38

Someone suggested me typing_inspect when I asked this question on SO:
https://stackoverflow.com/questions/52239007/in-python-3-7-how-do-i-check-that-x-typing-liststr-is-of-typing-list

**Comment by ilevkivskyi** [comment]
OK, this looks reasonable. I don't think there is a need for action here. You can just use `typing_inspect.get_origin(self.type) in (dict, typing.Dict)` as you do now. This is a bit unfortunate, but doesn't look critical.

**Comment by jbasko** [comment]
OK, no problem. Thanks for looking into this.
