### ISSUE TITLE
get_args doesn't work with custom Generics in 3.7

### ISSUE THREAD

**Issue by mjr129** [ilevkivskyi/typing_inspect#30]
Python version 3.7. 

Minimal example
------------------

    from typing import Generic, TypeVar
    import typing_inspect
        
    T = TypeVar( "T" )
        
    class MyGenericBase( Generic[T] ):
        pass
        
    class MyGeneric( MyGenericBase[int] ):
        pass
        
    print( typing_inspect.get_args( MyGeneric ) )

Actual result
----------------

    ( )

Expected result
----------------

    ( int, )

**Comment by ilevkivskyi** [comment]
This is actually expected behavior. What you want is probably https://github.com/ilevkivskyi/typing_inspect/issues/7
