### ISSUE TITLE
is_optional_type returns True for Union[Optional[xxx], yyy]

### ISSUE THREAD

**Issue by yukinarit** [ilevkivskyi/typing_inspect#38]
Hi ilevkivskyi,

It seems `is_optional_type` returns True for `Union[Optional[xxx], yyy]` as shown below.

```
>>> from typing_inspect import is_optional_type
>>> from typing import Union, Optional
>>> is_optional_type(Union[Optional[int], str])
True
```

Tested with typing_inspect 0.4.0

Is this an intended behaviour or bug? How should I do to distinguish  `Union[Optional[xxx], yyy]` from `Optional[zzz]` by `is_optional_type` and `is_union_type`?

Thank you,

**Comment by ilevkivskyi** [comment]
Yes, this is intentional, nested unions are flattened both at runtime and by static type checkers, and `Optional[X]` is literally `Union[X, None]` (also both at runtime and statically).
