### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by bgw** [ilevkivskyi/typing_inspect#43]
We'd like to use the features I added in #39 and #40 within Instagram, and it'd be easier to pull the changes in if there's a PyPI release containing them. Are there plans to cut a 0.4.1 or 0.5.0 release?

**Comment by ilevkivskyi** [comment]
I will probably make a release in next few weeks. Feel free to ping here if I will forget about this.

**Comment by ilevkivskyi** [comment]
OK, `typing_inspect` 0.5.0 is tagged and released. Please try it and let me know if somethnig is wrong!
