### ISSUE TITLE
Support Python 3.5 as well

### ISSUE THREAD

**Issue by mitar** [ilevkivskyi/typing_inspect#5]
Based on README, making a request. :-)

**Comment by ilevkivskyi** [comment]
Actually, it was tested and should work with Python 3.5.2/3.5.3 IIRC. It should not be very hard to keep this support, but supporting 3.5.1 is not so easy (because of internal typing API changes).

**Comment by mitar** [comment]
Hm, I tried on Python 3.5.2 (default, Oct 11 2016, 05:00:16).

**Comment by ilevkivskyi** [comment]
As you can see Python 3.5-dev is in ``.travis.yml`` and tests passed, so that it should work in at least oner of the most recent versions (although I didn't push anything after 3.5.4).
