### ISSUE TITLE
TypedDict - should it be imported from `typing_extensions` ?

### ISSUE THREAD

**Issue by kornicameister** [ilevkivskyi/typing_inspect#50]
It depends on `Python` but starting from `3.6` `TypedDict` can be exported via `typing_extensions` package and on `3.8` we have it builtin. Also `typing_extensions` variant is `3.8` compatible while `mypy_extensions` is not. What happens now is that we have `typed_dict_keys()` function that tries to get an entries of `TypedDict`, however it expects `TypedDict` from `mypy_extensions` thus `isintance` check will never work.

**Comment by kornicameister** [comment]
@ilevkivskyi should `mypy_extensions` even be a part of `requirements.txt`?

**Comment by JelleZijlstra** [comment]
`typing-inspect` should probably support TypedDict from both mypy-extensions and typing-extensions.

**Comment by ilevkivskyi** [comment]
> `typing-inspect` should probably support TypedDict from both mypy-extensions and typing-extensions.

Yes, I think it is best to support `TypedDict` from all possible import sources.
