### ISSUE TITLE
Adding `is_new_type`

### ISSUE THREAD

**Issue by kornicameister** [ilevkivskyi/typing_inspect#51]
I'd like to propose

```
def is_new_type(tt: t.Type[t.Any]) -> bool:
    return getattr(tt, '__supertype__', None) is not None
```

as an addition to this API. Perhaps it would make sense to also have a way to retrieve that `supertype`. I have tested that code (currently indirectly) in `Python 3.{6-9}` and seems to be working.

Opinions :)

**Comment by ilevkivskyi** [comment]
I like this idea, PRs are welcome.
