### ISSUE TITLE
`is_generic_type(List)` is False in 3.9

### ISSUE THREAD

**Issue by JelleZijlstra** [ilevkivskyi/typing_inspect#60]
```
In [7]: sys.version                                                                                                                                                                  
Out[7]: '3.9.0b1 (v3.9.0b1:97fe9cfd9f, May 18 2020, 20:39:28) \n[Clang 6.0 (clang-600.0.57)]'

In [8]: from typing import List                                                                                                                                                      

In [9]: typing_inspect.is_generic_type(List)                                                                                                                                         
Out[9]: False
```
Apparently in 3.9 `List` became an instance of `_SpecialGenericAlias` instead of `_GenericAlias`, which is what `typing_inspect` checks for.

**Comment by thatch** [comment]
This same bug has far-reaching effects and is the cause of https://github.com/Instagram/LibCST/issues/305 as well.

**Comment by thatch** [comment]
This is a little more interesting.  `_SpecialGenericAlias` doesn't have `__args__` on it, so in the trivial fix to consider `List` as well as `List[int]` as generic, `get_args` now fails with `AttributeError`

**Comment by thatch** [comment]
Jelle, I had a conversation with Łukasz and I don't feel like we have buy-in on this being a cpython bug.  I don't think there's a way to fix this in `typing_inspect`, can you help me with considering fixes and escalating?

**Comment by ilevkivskyi** [comment]
FWIW, a potential fix can be hard-coding some special cases. Technically, `typing_inspect` uses a bunch of _private_ APIs to provide a bit deeper level of introspection than the one provided by `typing`, so I can see why this is not an upstream bug.

I may not have time to work on this soon, but if someone has ideas for a robust fix, I will be glad to merge a PR.

**Comment by JelleZijlstra** [comment]
Similar to what Ivan said, I'm not sure why this can't be fixed in typing-inspect, for example by looking for the `_SpecialGenericAlias` class inside the implementation of `is_generic_type()`.

I ran into this doing some runtime type inspection in pyanalyze and worked around it with some 3.9-specific code: https://github.com/quora/pyanalyze/blob/master/pyanalyze/annotations.py#L225.

Is there a bugs.python.org issue about this?

**Comment by baldurmen** [comment]
FWIW, this means I can't build `typing_inspect` in Debian anymore :(

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972803

Hopefully someone can implement a fix soonish, since it won't move from unstable to testing until this is fixed.
