### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by pschanely** [ilevkivskyi/typing_inspect#65]
typing_inspect doesn't really work with Python 3.9 right now. There are issues like #60 and #64, but a variety of things need to be updated.
My initial survey (just guessing from poking at implementations; it would be better to have someone review/expand this list who is more intimately familiar with the code-level changes):
* The typing module in 3.9 introduces a new "_BaseGenericAlias" class that might more correctly correspond to typing_inspect's current uses of "_GenericAlias."
* Add support and tests for the new plain type hints (e.g. "list[int]" rather than "List[int]"). There seems to be a new "GenericAlias" class (that extends no other classes) for these kind of annotations.
* Get the current test suite to pass under 3.9.
* Add 3.9 to the travis config for regression testing.

Any volunteers willing to give it a try? @ilevkivskyi - any additional guidance? What's wrong/missing in my above list?

**Comment by Apteryks** [comment]
Adding this bit of info here, in case it helps: currently, there's only one test suite failure:

```
======================================================================
FAIL: test_generic (test_typing_inspect.IsUtilityTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-typing-inspect-0.6.0.drv-0/typing_inspect-0.6.0/test_typing_inspect.py", line 133, in test_generic
    self.sample_test(is_generic_type, samples, nonsamples)
  File "/tmp/guix-build-python-typing-inspect-0.6.0.drv-0/typing_inspect-0.6.0/test_typing_inspect.py", line 123, in sample_test
    self.assertTrue(fun(s), msg=msg % (fun.__name__, str(s), 'True'))
AssertionError: False is not true : Error asserting that is_generic_type(typing.Mapping) is True

----------------------------------------------------------------------
```

**Comment by bnavigator** [comment]
> * The typing module in 3.9 introduces a new "_BaseGenericAlias" class that might more correctly correspond to typing_inspect's current uses of "_GenericAlias."

#69

> * Get the current test suite to pass under 3.9.

See https://github.com/bnavigator/typing_inspect/runs/2159879881 for a sucessful Travis CI run on Python 3.9 when #68 and #69 are combined.

**Comment by ilevkivskyi** [comment]
Actually reopening because one bullet item from the list is still missing:
* Add support and tests for the new plain type hints (e.g. "list[int]" rather than "List[int]")

@bnavigator Could you please make one more PR :-)

**Comment by martinjm97** [comment]
Support for `list[int]` and similar would be very helpful. It should be a matter of changing `isinstance(tp, _GenericAlias)` to`isinstance(tp, (_GenericAlias, types.GenericAlias))`.

**Comment by ilevkivskyi** [comment]
I also uploaded a new version to PyPI https://pypi.org/project/typing-inspect/0.7.0/, please test! If you will find some problems, please open separate issues.
