### ISSUE TITLE
Get hierarchy of arguments

### ISSUE THREAD

**Issue by mitar** [ilevkivskyi/typing_inspect#7]
If I want to compare two types which are like:

```
class Parent:
  pass

class Child(Parent):
  pass

class Foo(Sequence[Child]):
  pass

compare(Foo, Sequence[Parent])
```

It seems hard to do any comparison:
* `inspect.getmro` of `Foo` does not return `Sequence[str]`
* I can use `get_generic_bases` to manually traverse parent classes, but doing that in MRO order is tricky (#6)
* but what would ideally be is that I would have a method which would return the hierarchy of types and their arguments, so that I could find out that Foo inherits from `Sequence[Child]`, and that there is an argument `Child` and then compare that with `Sequence[Parent]`; it seems pretty tricky with current typing_inspect to get from `Foo` to `Child` as an argument, no?

**Comment by ilevkivskyi** [comment]
This seems to be quite complicated, so that this is quite low priority. I think #6 would be enough for most use cases.

**Comment by Stewori** [comment]
Depending on what ``compare`` means, note this may also be possible with [pytypes](https://github.com/Stewori/pytypes):

```
class Parent:
  pass

class Child(Parent):
  pass

class Foo(Sequence[Child]):
  pass

print(pytypes.is_subtype(Foo, Sequence[Parent])) # prints True
print(pytypes.is_subtype(Foo, Sequence[int])) # prints False
```

**Comment by ilevkivskyi** [comment]
@mitar Is ``pytypes.is_subtype`` what you wanted? If yes, then I propose to close this and instead implement #6.

**Comment by mitar** [comment]
I went with `pytypes.is_subtype`.
