### ISSUE TITLE
Breaks `marshmallow_dataclass.NewType`

### ISSUE THREAD

**Issue by gabor-akeero** [ilevkivskyi/typing_inspect#91]
In [is_new_type](https://github.com/ilevkivskyi/typing_inspect/blob/b24da20b0f137e00cd8c511843ff52cb92dcf470/typing_inspect.py#L287) there is an explicit check for the module name being either `typing` or `typing_extensions`, so types created via [marshmallow_dataclass.NewType](https://github.com/lovasoa/marshmallow_dataclass/blob/ad4d654561a8f6514f7ee63e90642ee3417ccf3f/marshmallow_dataclass/__init__.py#L773) are no longer recognised, and therefore cannot be used in marshmallow dataclasses.

This check on `__module__` makes it impossible to define and use any custom `NewType` implementations, even if they are intended to be accepted as `NewType`.

As the pre-3.10 implementations of `typing.NewType` define only two extra attributes `__name__` and `__supertype__`, I'd suggest a check on these two (besides `__qualname__`), and on their types:
```
... isinstance(getattr(tp, '__supertype__', None), type) and isinstance(getattr(tp, '__name__'), str) and ...
```

This would check everything that we can be sure of, and wouldn't block the custom `NewType`-implementations.

**Comment by vit-zikmund** [comment]
FYI, my fix for `marshmallow_dataclass` has been cherry-picked into https://github.com/lovasoa/marshmallow_dataclass/pull/211 and merged to master. Unless reverted, the fix fill will be available with any next release (which I have no control of, tho).

**Comment by dairiki** [comment]
> FYI, my fix for `marshmallow_dataclass` has been cherry-picked into [lovasoa/marshmallow_dataclass#211](https://github.com/lovasoa/marshmallow_dataclass/pull/211) and merged to master. Unless reverted, the fix fill will be available with any next release (which I have no control of, tho).

A release has just been made of marshmallow-dataclass 8.5.9 that includes @vit-zikmund’s fixes for `marshmallow_dataclass.NewType`.

**Comment by gabor-akeero** [comment]
This issue has been fixed at `marshmallow_dataclass`
